### PR TITLE
Permits to add xmlsec1 node_xpath options when verify assertion response.

### PR DESCRIPTION
**Pull request by toopy**
@bersace for review.

### CODE REVIEW

**Comment by bersace** [comment]
Tests ?

**Comment by toopy** [comment]
@bersace with tests ;)

note: remains 2 failing tests for 478 ok. (hard coded sec values, not documented (for next time test sprint;)).

**Comment by bersace** [comment]
:+1:

**Comment by bersace** [comment]
Question : node_id et node_xpath sont incompatible à priori. Donc que se passe-t-il si les deux sont définis ?

**Comment by toopy** [comment]
@bersace it only handle node_xpath if both are passed: https://github.com/novapost/pysaml2/pull/1/files#diff-23342a17f6a3ddc87d6a52e16795da14R767

**Pull request merged**
